title: Overt Network
email: hello@overtnetwork.com
description: >- # this means to ignore newlines until "baseurl:"
  Reach and engage Catholics with profound and actionable videos. #LogosRising
url: "https://overtnetwork.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: overtTV

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed

minima:
  social_links:
    twitter: overt_tv
    facebook: overttv
    instagram: overt_tv

    youtube: overtTV
    youtube_channel: UCft-DKeEWYaV8y3oVPkFZbw
    youtube_channel_name: OvertTV

google_analytics: UA-87360452-3