title: Overt TV
email: hello@overtnetwork.com
description: >- # this means to ignore newlines until "baseurl:"
  Reach and engage Catholics with profound and actionable videos. #LogosRising
url: "https://overtnetwork.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

sass:
  style: compressed


twitter_username: "Overt_TV"
facebook_username: "OvertTV"
instagram_username: "overt_TV"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag


google_analytics: UA-87360452-3